### ISSUE TITLE
Passing globe ref breaks links and throws "Maximum update depth exceeded" warning

### ISSUE THREAD

**Issue by FalseFeint** [vasturiano/react-globe.gl#179]
**Describe the bug**
I'm trying to get a globe to automatically spin and I've gotten it work but I've noticed the following:
1. I'm getting a warning in console stating: **Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.**
2. Links on the rest of the page no longer work. If I hover over them the correct URL is displayed in the bottom left of screen but clicking on them does not change URLs

**Note:** I'm using next and react release candidates and I'm new to both next and react in general. This could easily be an error due to my ignorance.

**To Reproduce**
After eliminating chunks of code, I've discovered that passing a globe ref is causing the behavior described above. Here is some code:
```
'use client';
import { useRef } from 'react';
import Globe from 'react-globe.gl';

const TestGlobe = () => {
  const globeEl = useRef();

  return <Globe ref={globeEl} />;
};

export default TestGlobe;
```
which results in the following warning:
```
71845 app-index.tsx:30 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at http://localhost:3001/_next/static/chunks/node_modules_4e2c9c._.js:213:193
    at TestGlobe (http://localhost:3001/_next/static/chunks/_1eb686._.js:20:193)
    at div
    at div
    at div
    at Home (Server)
    at main
    at div
    at Page (Server)
    at InnerLayoutRouter (http://localhost:3001/_next/static/chunks/node_modules_d71c4a._.js:16906:11)
    at RedirectErrorBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:5015:9)
    at RedirectBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:5023:11)
    at NotFoundErrorBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:5260:9)
    at NotFoundBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:5268:11)
    at LoadingBoundary (http://localhost:3001/_next/static/chunks/node_modules_d71c4a._.js:17010:11)
    at ErrorBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:4729:11)
    at InnerScrollAndFocusHandler (http://localhost:3001/_next/static/chunks/node_modules_d71c4a._.js:16817:9)
    at ScrollAndFocusHandler (http://localhost:3001/_next/static/chunks/node_modules_d71c4a._.js:16892:11)
    at RenderFromTemplateContext (http://localhost:3001/_next/static/chunks/node_modules_d71c4a._.js:17136:44)
    at OuterLayoutRouter (http://localhost:3001/_next/static/chunks/node_modules_d71c4a._.js:17030:11)
    at O (http://localhost:3001/_next/static/chunks/node_modules_d71c4a._.js:10976:24)
    at z (http://localhost:3001/_next/static/chunks/node_modules_d71c4a._.js:10971:171)
    at ThemeProvider (http://localhost:3001/_next/static/chunks/_dba0f8._.js:600:26)
    at body
    at html
    at RootLayout (Server)
    at RedirectErrorBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:5015:9)
    at RedirectBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:5023:11)
    at NotFoundErrorBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:5260:9)
    at NotFoundBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:5268:11)
    at DevRootNotFoundBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:5328:11)
    at ReactDevOverlay (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:12004:9)
    at HotReload (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:12783:11)
    at Router (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:13100:11)
    at ErrorBoundaryHandler (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:4683:9)
    at ErrorBoundary (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:4729:11)
    at AppRouter (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:13481:13)
    at ServerRoot (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:13731:27)
    at Root (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:13735:11)
    at ReactDevOverlay (http://localhost:3001/_next/static/chunks/node_modules_next_dist_client_35ffaf._.js:12004:9)
```
Here is my original code. It contains more than the automatic spinning:

```
'use client';
import * as topojson from 'topojson';
import pointsData from './random-locations.json';
import { useState, useEffect, useRef, forwardRef } from 'react';
import * as THREE from 'three';
import Globe from 'react-globe.gl';

const min = 5000;
const max = 10000;
const sliceData = pointsData
  .sort(() => (Math.random() > 0.5 ? 1 : -1))
  .slice(20, 90);

const arcsData = sliceData.map(() => {
  const randStart = Math.floor(Math.random() * sliceData.length);
  const randEnd = Math.floor(Math.random() * sliceData.length);
  const randTime = Math.floor(Math.random() * (max - min + 1) + min);
  return {
    startLat: sliceData[randStart].lat,
    startLng: sliceData[randStart].lng,
    endLat: sliceData[randEnd].lat,
    endLng: sliceData[randEnd].lng,
    time: randTime,
    color: ['#ffffff00', '#888888', '#ffffff00'],
  };
});

const MyGlobe = () => {
  const globeEl = useRef();
  const [globeReady, setGlobeReady] = useState(false);
  const [landPolygons, setLandPolygons] = useState([]);

  const startTime = 1000;
  const polygonsMaterial = new THREE.MeshBasicMaterial({
    color: 'darkgrey',
    side: THREE.DoubleSide,
  });
  const globeMaterial = new THREE.MeshBasicMaterial({
    color: new THREE.Color('white'),
  });

  useEffect(() => {
    if (!globeEl.current) {
      return;
    }
    globeEl.current.pointOfView(
      {
        lat: 39.609913,
        lng: -105.962477,
        altitude: 2.5,
      },
      startTime
    );
    // Auto-rotate
    globeEl.current.controls().autoRotate = true;
    globeEl.current.controls().autoRotateSpeed = 1;
    globeEl.current.controls().enableZoom = false;
  }, [globeReady]);

  useEffect(() => {
    // load data
    fetch('//unpkg.com/world-atlas/land-110m.json')
      .then((res) => res.json())
      .then((landTopo) => {
        setLandPolygons(
          topojson.feature(landTopo, landTopo.objects.land).features
        );
      });
  }, []);

  return (
    <div>
      <Globe
        ref={globeEl}
        onGlobeReady={() => setGlobeReady(true)}
        height={300}
        width={300}
        atmosphereColor="#efefef"
        atmosphereAltitude={0.5}
        backgroundColor="rgba(0,0,0,0)"
        globeMaterial={globeMaterial}
        polygonsData={landPolygons}
        polygonCapMaterial={polygonsMaterial}
        polygonSideColor={() => 'rgba(200, 200, 200, 0)'}
        pointsMerge={true}
        pointsData={pointsData}
        pointAltitude={0.01}
        pointRadius={0.2}
        pointResolution={5}
        pointColor={() => '#888888'}
        arcsData={arcsData}
        arcAltitudeAutoScale={0.3}
        arcColor="color"
        arcStroke={0.5}
        arcDashGap={2}
        arcDashAnimateTime="time"
      />
    </div>
  );
};

export default MyGlobe;
```
Relevant packages (**Note:** I'm using next and react release candidates):
```
"next": "15.0.0-rc.0",
"next-themes": "^0.3.0",
"radix-ui": "^1.0.1",
"react": "19.0.0-rc-f994737d14-20240522",
"react-dom": "19.0.0-rc-f994737d14-20240522",
"react-globe.gl": "^2.27.2",
"three": "^0.167.1",
```

**Expected behavior**
Passing globe ref should not result in warning and more importantly not break links. I think the two are related, but I'm not positive.

**Screenshots**
![image](https://github.com/user-attachments/assets/103e52ad-516c-4521-8278-8ab67a915bba)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome

**Comment by FalseFeint** [comment]
I downgraded next, react, and react-dom to the latest release (instead of RCs) and the warning has disappeared and links work again. I still don't understand what is causing things to break in the release candidates :/

**Comment by slavanga** [comment]
I'm getting the same error after updating next to `v15.0.1`

**Comment by rakshit087** [comment]
Hey! Which version worked for you? I am getting the same error, not sure what is causing it.

**Comment by slavanga** [comment]
@rakshit087 next `v14.2.17` and react-globe.gl `v2.27.4` are working.
the error starts appearing from next v15. most likely this is related to React v19

**Comment by vasturiano** [comment]
A fix has been applied. If you upgrade to the latest version of the lib (`2.27.5`) you shouldn't experience the warnings any more, when using next.js 15.
