### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by brendonco** [vasturiano/react-globe.gl#27]
Running the library sometimes render the globe, sometimes throw an exception.  Are you using global window somewhere in your code?

Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.

```
import Globe from 'react-globe.gl';

const World = (props) => <Globe {...props} />;

export default World;
```

```
 at Object.<anonymous> (file:///Users/sample/node_modules/three-geojson-geometry/dist/three-geojson-geometry.common.js:152:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (file:///Users/sample/node_modules/three-globe/dist/three-globe.common.js:6:28)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (file:///Users/sample/node_modules/globe.gl/dist/globe.gl.common.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
getNodeError @ nodeStackFrames.js?aca3:39
eval @ index.tsx?8abf:326
setTimeout (async)
_callee$ @ index.tsx?8abf:312
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?c973:3
_next @ asyncToGenerator.js?c973:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?c973:13
_next @ asyncToGenerator.js?c973:25
eval @ asyncToGenerator.js?c973:32
eval @ asyncToGenerator.js?c973:21
_default @ index.js:442
eval @ next-dev.js?53bc:31
eval @ next-dev.js?53bc:31
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1609233259916:2107
__webpack_require__ @ webpack.js?ts=1609233259916:873
checkDeferredModules @ webpack.js?ts=1609233259916:46
webpackJsonpCallback @ webpack.js?ts=1609233259916:33
(anonymous) @ webpack.js?ts=1609233259916:1015
(anonymous) @ webpack.js?ts=1609233259916:1023
unfetc
```

**Comment by brendonco** [comment]
never mind seems like a nextjs loading the react-globe.gl which uses window.

**Comment by MatteoGauthier** [comment]
How did you fixed this @brendonco ?
